### PR TITLE
add waypoint navigate

### PR DESCRIPTION
**Pull request by ReChavers**
new format wayopint yaml

### CODE REVIEW

**Comment by yeehaa123** [comment]
Hi Reika,

Looks great! A couple of formatting issues that need to be solved, before I can merge. 

- The indendation for instructions and resources is off. Should be the same as title and introduction
- If there's a colon in a sentence, it either needs to be wrapped in quotation marks or on a separate line with a pipe
- resources no longer have authors.
- uptodateness should be up_to_date

Cheers,

JH

**Comment by yeehaa123** [comment]
Okay, Charlotte says we should have an author for legal purposes... She's probably right!

**Comment by ReChavers** [comment]
Have made the changes you requested

**Comment by yeehaa123** [comment]
A couple of more changes before I can merge:

- Instruction needs to be instruction*s*
- clarity (etc). should be nested under a key called criteria
- The part after a pipe (|) should be indented

**Comment by yeehaa123** [comment]
another point:
- author should be authors and always an array

**Pull request merged**
