### PR TITLE
Tour guide - with appState

### PR DESCRIPTION
**Pull request by Zaturrby**
@yeehaa123 Made the tour choice dependent on the appState. The tour is now split up in the appropriate levels. 

I did encounter a problem with dynamically setting the tour though, the library should provide an interface for it, but it isn't available in the npm package yet. A bit more annoying is that the tour is statically set into the class by the mixin, which gives every instance of the class Tour the same tour. This is not what we needed, so I improvised a bit. The mixin is now called with an empty tour, and then the getInitialState method sets the steps of each distinct tour element. It all works as far as I can tell, but I suppose a quick look at it might be wise.

### CODE REVIEW

**Comment by Zaturrby** [comment]
@yeehaa123 I've got a question by the way, is there some error catching in the app? I spelled resource like resourse and it didn't give an error (15941ad). It annoyed me for quite a bit, it just halted the app at the resource level, and I noticed the error quite late. It might also be react catching stuff, but I just want to be sure that there isn't some nice 'don't suppress my mistakes, and show me exactly where they are' switch somewhere. I also wondered: is there a way that I could / should use those amazing tests you've talked all about to my benefit?

**Comment by yeehaa123** [comment]
@Zaturrby I noticed the admission of that function in the tour library too. Greg and I copy-and-pasted it in from the github repo, but it was still quite buggy...

**Comment by yeehaa123** [comment]
Cool PR. Works like a charm!

**Comment by yeehaa123** [comment]
ps. no error handling in the app, tests help a lot with that.. I should think of a good strategy though.

**Pull request merged**
