### PR TITLE
Tour guide

### PR DESCRIPTION
**Pull request by ReChavers**

### CODE REVIEW

**Comment by yeehaa123** [comment]
@Zaturrby Can you explain why you moved the tourselector down a level. I actually don't want this, because it leads to complications elsewhere. Were there any problems that made this necessary?

**Comment by Zaturrby** [comment]
@yeehaa123 No, I just copied the syntax of the syntax of that level, so it seemed more logical there to me. Will move it back up one level.

**Comment by Zaturrby** [comment]
@yeehaa123 Tour is now in the unacademicContainer. 397fc5f

**Comment by yeehaa123** [comment]
The bubbles continue even when you are on a different level. This should not happen. The reason for the tourselector is that we can make a tour component and corresponding tour for each individual level, deciding which one to render on the basis of the appstate (level). @ReChavers @Zaturrby could you fix this.

**Pull request merged**
